apiVersion: v1
kind: Service
metadata:
        name: vproapp
        namespace: vprofile
        labels:
                app: frontend
spec:
        selector:
                app: frontend
        ports:
                - targetPort: 8080
                  port: 80
                  protocol: TCP
        type: LoadBalancer

