apiVersion: v1
kind: Service
metadata:
        namespace: vprofile
        name: vprodb
        labels:
                app: backend
spec:
        ports:
                - targetPort: 3306
                  port: 3306
                  protocol: TCP
        selector:
                app: backend
        type: ClusterIP



