apiVersion: v1
kind: Service
metadata:
        name: vpromq01
        namespace: vprofile
        labels:
                app: rbmq
spec:
        selector:
                app: rbmq
        ports:
                - targetPort: 15672
                  port: 15672
                  protocol: TCP
        type: ClusterIP

